### ISSUE TITLE
Numpy_Toolkit: prototype numpy adapter

### ISSUE THREAD

**Issue by epignatelli** [BHoM/Numpy_Toolkit#1]
#### Description:

Add a prototype of the `NumpyAdapter`. 
The plan is to wrap `numpy` around a `AdapterCompute` component in the UIs.

The project requires a few iterations to get it right, as we are experimenting with something new.

**Comment by tg359** [comment]
Glad to see something like this here! What's the plan for running Numpy? Are we going to package something like a mini Python environment in BHoM, capable of running Numpy?

**Comment by epignatelli** [comment]
Yeah, Numpy is coming to visual programming (and Excel 🤖), together with some big tools for deep learning: Tensorflow and Keras, Torch, and ScikitLearn 🚀 

The plan is to use the [SciSharp stack](https://github.com/SciSharp) - the guys have been doing an incredible work in creating the .NET bindings for most of these libraries.

The python backend is solved through [Python.Included](https://github.com/henon/Python.Included). I am still trying to figure that out, but that's the way!

I'll send you some stuff to begin with. Let's have a call one of these days!
